### ISSUE TITLE
reconsider transitive dependency to slf4j-api

### ISSUE THREAD

**Issue by ArtsiomCh** [avaje-common/avaje-agentloader#8]
My project works in the environment with different Classloaders: it's a plugin for IntelliJ IDEA and classloader for my plugin and classloader for the main app(where slf4j is loaded) are different. That means slf4j is already provided by the environment for my plugin and I shouldn't load it as an explicit dependency.
When I create a dependency on `avaje-agentloader` in my project in gradle.build, for example: 
```compile group: 'org.avaje', name: 'avaje-agentloader', version: '3.0.1'```
I got `slf4j-api` as a dependency as well. That cause next exception:
```
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader com.intellij.ide.plugins.cl.PluginClassLoader @6a34f06b (instance of com.intellij.ide.plugins.cl.PluginClassLoader, child of 'bootstrap') of the current class, org/slf4j/LoggerFactory, and the class loader com.intellij.util.lang.UrlClassLoader @2ac273d3 (instance of com.intellij.util.lang.UrlClassLoader, child of 'platform' jdk.internal.loader.ClassLoaders$PlatformClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
```
When I build `avaje-agentloader-3.0.2-SNAPSHOT.jar` from the source excluding the explicit dependency to slf4j and link it to project as just binary library everething works as expected.

Another way I found to just exclude transitive dependency in Gradle:
```    compile ('org.avaje:avaje-agentloader:3.0.1') {exclude group: 'org.slf4j'}```
But would be good to have that transitive dependency to slf4j-api optional out-of-box...

Possible solution would be adding ` <scope>provided</scope>` to slf4j-api dependency. But I didn't test that and that might break other use cases...

PS Thank you for the great library! Saved me a lot of work when moving to JDK11.

**Comment by rbygrave** [comment]
> adding <scope>provided</scope> to slf4j-api dependency

I don't have a problem with that.  We could release that with a major version bump I'd say.
